# Flow for deploying the app to https://ue-remote-app.adobe.net
name: Deploy to https://ue-remote-app.adobe.net
on:
  push:
    branches:
      - pilot1
    paths:
      - 'build/index.html'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to https://ue-remote-app.adobe.net
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: './build'
          production-branch: pilot1
          github-token: ${{ secrets.AUTH_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
